services:
  redis_container:
    image: redis:latest
    container_name: picpic_redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf
  mysql_container:
    image: mysql:8.0
    container_name: picpic_mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dev
      TZ: Asia/Seoul
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  openvidu_container:
    image: openvidu/openvidu-dev:2.28.0
    ports:
      - "4443:4443"
    environment:
      - OPENVIDU_SECRET=${OPEN_VIDU_SECRET}
      - DOMAIN_OR_PUBLIC_IP=localhost
      - OPENVIDU_WEBHOOK=true
      - OPENVIDU_WEBHOOK_ENDPOINT=http://host.docker.internal:8080/api/webhooks/openvidu
      - OPENVIDU_WEBHOOK_EVENTS=["participantJoined","participantLeft"]
      - "OPENVIDU_WEBHOOK_HEADERS=[\"Authorization: ${OPEN_VIDU_TOKEN}\"]"
      - OPENVIDU_RECORDING=false
      - OPENVIDU_CDR=false
